Tidy up LabelledSlider
CLion was showing some of the constructors as not used but they are
used in AnalyserSettings.h but in the form that means they are not
explicitly called and I think that this is just not detected by the
IDE.

When removing the constructors marked as unused, I was getting the
following error message:

  JUCECmakeRepoPrototype\Apps\mbk\Source\Loudness\AnalyserSettings.h(22): error C2665: 'Components::LabelledSlider::LabelledSlider': no overloaded function could convert all the argument types